// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zruijotggxoqellebtqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpydWlqb3RnZ3hvcWVsbGVidHFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTU2NzcsImV4cCI6MjA2MjM3MTY3N30.V8ucadK-SLF6gWvX80x5EllrDGXZknGk5UNpNEa3GZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);